// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptGroupInviteReducer from "../accept_group_invite_reducer";
import AddCityReducer from "../add_city_reducer";
import AddClubReducer from "../add_club_reducer";
import AddSnackReducer from "../add_snack_reducer";
import ApproveInviteRequestReducer from "../approve_invite_request_reducer";
import BeginRatingReducer from "../begin_rating_reducer";
import ClearClubMoodReducer from "../clear_club_mood_reducer";
import CreateBackupCodeReducer from "../create_backup_code_reducer";
import CreateGroupReducer from "../create_group_reducer";
import CreateGroupInviteReducer from "../create_group_invite_reducer";
import CreateMatchFixtureReducer from "../create_match_fixture_reducer";
import DeleteMatchFixtureReducer from "../delete_match_fixture_reducer";
import EndRatingReducer from "../end_rating_reducer";
import EnterMatchResultReducer from "../enter_match_result_reducer";
import JoinClubReducer from "../join_club_reducer";
import KickGroupMemberReducer from "../kick_group_member_reducer";
import LeaveClubReducer from "../leave_club_reducer";
import LeaveGroupReducer from "../leave_group_reducer";
import RedeemBackupCodeReducer from "../redeem_backup_code_reducer";
import RegenerateGroupInviteReducer from "../regenerate_group_invite_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RejectInviteRequestReducer from "../reject_invite_request_reducer";
import RenameGroupReducer from "../rename_group_reducer";
import RequestTeamInviteReducer from "../request_team_invite_reducer";
import RevokeGroupInviteReducer from "../revoke_group_invite_reducer";
import SeedClubsReducer from "../seed_clubs_reducer";
import SendReactionReducer from "../send_reaction_reducer";
import SetAvatarReducer from "../set_avatar_reducer";
import SetPositionReducer from "../set_position_reducer";
import ShareSeasonWithCrewReducer from "../share_season_with_crew_reducer";
import SimulateMatchReducer from "../simulate_match_reducer";
import SubmitPredictionReducer from "../submit_prediction_reducer";
import SubmitRatingReducer from "../submit_rating_reducer";
import ToggleFollowReducer from "../toggle_follow_reducer";
import ToggleLikeReducer from "../toggle_like_reducer";
import ToggleRatingReactionReducer from "../toggle_rating_reaction_reducer";
import VoteClubMoodReducer from "../vote_club_mood_reducer";
import VoteRatingReducer from "../vote_rating_reducer";

export type AcceptGroupInviteParams = __Infer<typeof AcceptGroupInviteReducer>;
export type AddCityParams = __Infer<typeof AddCityReducer>;
export type AddClubParams = __Infer<typeof AddClubReducer>;
export type AddSnackParams = __Infer<typeof AddSnackReducer>;
export type ApproveInviteRequestParams = __Infer<typeof ApproveInviteRequestReducer>;
export type BeginRatingParams = __Infer<typeof BeginRatingReducer>;
export type ClearClubMoodParams = __Infer<typeof ClearClubMoodReducer>;
export type CreateBackupCodeParams = __Infer<typeof CreateBackupCodeReducer>;
export type CreateGroupParams = __Infer<typeof CreateGroupReducer>;
export type CreateGroupInviteParams = __Infer<typeof CreateGroupInviteReducer>;
export type CreateMatchFixtureParams = __Infer<typeof CreateMatchFixtureReducer>;
export type DeleteMatchFixtureParams = __Infer<typeof DeleteMatchFixtureReducer>;
export type EndRatingParams = __Infer<typeof EndRatingReducer>;
export type EnterMatchResultParams = __Infer<typeof EnterMatchResultReducer>;
export type JoinClubParams = __Infer<typeof JoinClubReducer>;
export type KickGroupMemberParams = __Infer<typeof KickGroupMemberReducer>;
export type LeaveClubParams = __Infer<typeof LeaveClubReducer>;
export type LeaveGroupParams = __Infer<typeof LeaveGroupReducer>;
export type RedeemBackupCodeParams = __Infer<typeof RedeemBackupCodeReducer>;
export type RegenerateGroupInviteParams = __Infer<typeof RegenerateGroupInviteReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RejectInviteRequestParams = __Infer<typeof RejectInviteRequestReducer>;
export type RenameGroupParams = __Infer<typeof RenameGroupReducer>;
export type RequestTeamInviteParams = __Infer<typeof RequestTeamInviteReducer>;
export type RevokeGroupInviteParams = __Infer<typeof RevokeGroupInviteReducer>;
export type SeedClubsParams = __Infer<typeof SeedClubsReducer>;
export type SendReactionParams = __Infer<typeof SendReactionReducer>;
export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetPositionParams = __Infer<typeof SetPositionReducer>;
export type ShareSeasonWithCrewParams = __Infer<typeof ShareSeasonWithCrewReducer>;
export type SimulateMatchParams = __Infer<typeof SimulateMatchReducer>;
export type SubmitPredictionParams = __Infer<typeof SubmitPredictionReducer>;
export type SubmitRatingParams = __Infer<typeof SubmitRatingReducer>;
export type ToggleFollowParams = __Infer<typeof ToggleFollowReducer>;
export type ToggleLikeParams = __Infer<typeof ToggleLikeReducer>;
export type ToggleRatingReactionParams = __Infer<typeof ToggleRatingReactionReducer>;
export type VoteClubMoodParams = __Infer<typeof VoteClubMoodReducer>;
export type VoteRatingParams = __Infer<typeof VoteRatingReducer>;

