// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActivityKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  get kind() {
    return ActivityKind;
  },
  clubId: __t.u64().name("club_id"),
  userId: __t.u64().name("user_id"),
  snackId: __t.u64().name("snack_id"),
  text: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
