// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  homeClubId: __t.u64().name("home_club_id"),
  awayClubId: __t.u64().name("away_club_id"),
  homeScore: __t.u32().name("home_score"),
  awayScore: __t.u32().name("away_score"),
  seed: __t.u64(),
  createdBy: __t.u64().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  ballX: __t.f32().name("ball_x"),
  ballY: __t.f32().name("ball_y"),
  ballTargetX: __t.f32().name("ball_target_x"),
  ballTargetY: __t.f32().name("ball_target_y"),
  phase: __t.string(),
  phaseSetAt: __t.timestamp().name("phase_set_at"),
  lastActionPlayerId: __t.u64().name("last_action_player_id"),
  lastActionSide: __t.string().name("last_action_side"),
  ballCarrierId: __t.u64().name("ball_carrier_id"),
  possessionSide: __t.string().name("possession_side"),
  nextDecisionAt: __t.timestamp().name("next_decision_at"),
  simPausedUntil: __t.timestamp().name("sim_paused_until"),
  isLive: __t.bool().name("is_live"),
});
