// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptGroupInviteReducer from "./accept_group_invite_reducer";
import AddCityReducer from "./add_city_reducer";
import AddClubReducer from "./add_club_reducer";
import AddSnackReducer from "./add_snack_reducer";
import ApproveInviteRequestReducer from "./approve_invite_request_reducer";
import BeginRatingReducer from "./begin_rating_reducer";
import ClearClubMoodReducer from "./clear_club_mood_reducer";
import CreateGroupReducer from "./create_group_reducer";
import CreateGroupInviteReducer from "./create_group_invite_reducer";
import CreateMatchFixtureReducer from "./create_match_fixture_reducer";
import DeleteMatchFixtureReducer from "./delete_match_fixture_reducer";
import EndRatingReducer from "./end_rating_reducer";
import EnterMatchResultReducer from "./enter_match_result_reducer";
import JoinClubReducer from "./join_club_reducer";
import KickGroupMemberReducer from "./kick_group_member_reducer";
import LeaveClubReducer from "./leave_club_reducer";
import LeaveGroupReducer from "./leave_group_reducer";
import RegenerateGroupInviteReducer from "./regenerate_group_invite_reducer";
import RegisterUserReducer from "./register_user_reducer";
import RejectInviteRequestReducer from "./reject_invite_request_reducer";
import RenameGroupReducer from "./rename_group_reducer";
import RequestTeamInviteReducer from "./request_team_invite_reducer";
import RevokeGroupInviteReducer from "./revoke_group_invite_reducer";
import SeedClubsReducer from "./seed_clubs_reducer";
import SendReactionReducer from "./send_reaction_reducer";
import SetAvatarReducer from "./set_avatar_reducer";
import SetPositionReducer from "./set_position_reducer";
import ShareSeasonWithCrewReducer from "./share_season_with_crew_reducer";
import SimulateMatchReducer from "./simulate_match_reducer";
import SubmitPredictionReducer from "./submit_prediction_reducer";
import SubmitRatingReducer from "./submit_rating_reducer";
import ToggleFollowReducer from "./toggle_follow_reducer";
import ToggleLikeReducer from "./toggle_like_reducer";
import VoteClubMoodReducer from "./vote_club_mood_reducer";
import VoteRatingReducer from "./vote_rating_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActivityEventRow from "./activity_event_table";
import CityRow from "./city_table";
import ClubRow from "./club_table";
import ClubMembershipRow from "./club_membership_table";
import ClubMoodRow from "./club_mood_table";
import FollowRow from "./follow_table";
import FootballMatchRow from "./football_match_table";
import GroupRow from "./group_table";
import GroupInviteRow from "./group_invite_table";
import GroupInviteRevealRow from "./group_invite_reveal_table";
import GroupMembershipRow from "./group_membership_table";
import InviteRequestRow from "./invite_request_table";
import MatchEventRow from "./match_event_table";
import MatchFixtureRow from "./match_fixture_table";
import MatchPlayerRow from "./match_player_table";
import MatchPredictionRow from "./match_prediction_table";
import ProvinceRow from "./province_table";
import RateLimitRow from "./rate_limit_table";
import RatingRow from "./rating_table";
import RatingIntentRow from "./rating_intent_table";
import RatingPingRow from "./rating_ping_table";
import RatingTagRow from "./rating_tag_table";
import RatingVoteRow from "./rating_vote_table";
import SessionRow from "./session_table";
import SnackRow from "./snack_table";
import SnackLikeRow from "./snack_like_table";
import SnackStatsRow from "./snack_stats_table";
import UserRow from "./user_table";
import UserPositionRow from "./user_position_table";
import UserReactionRow from "./user_reaction_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activity_event: __table({
    name: 'activity_event',
    indexes: [
      { accessor: 'id', name: 'activity_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'activity_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivityEventRow),
  city: __table({
    name: 'city',
    indexes: [
      { accessor: 'id', name: 'city_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'city_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CityRow),
  club: __table({
    name: 'club',
    indexes: [
      { accessor: 'id', name: 'club_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'club_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClubRow),
  club_membership: __table({
    name: 'club_membership',
    indexes: [
      { accessor: 'id', name: 'club_membership_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'club_membership_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClubMembershipRow),
  club_mood: __table({
    name: 'club_mood',
    indexes: [
      { accessor: 'id', name: 'club_mood_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'club_mood_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClubMoodRow),
  follow: __table({
    name: 'follow',
    indexes: [
      { accessor: 'id', name: 'follow_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'follow_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FollowRow),
  football_match: __table({
    name: 'football_match',
    indexes: [
      { accessor: 'id', name: 'football_match_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'football_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FootballMatchRow),
  group: __table({
    name: 'group',
    indexes: [
      { accessor: 'id', name: 'group_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'group_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupRow),
  group_invite: __table({
    name: 'group_invite',
    indexes: [
      { accessor: 'id', name: 'group_invite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'group_invite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupInviteRow),
  group_invite_reveal: __table({
    name: 'group_invite_reveal',
    indexes: [
      { accessor: 'invite_id', name: 'group_invite_reveal_invite_id_idx_btree', algorithm: 'btree', columns: [
        'inviteId',
      ] },
    ],
    constraints: [
      { name: 'group_invite_reveal_invite_id_key', constraint: 'unique', columns: ['inviteId'] },
    ],
  }, GroupInviteRevealRow),
  group_membership: __table({
    name: 'group_membership',
    indexes: [
      { accessor: 'id', name: 'group_membership_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'group_membership_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupMembershipRow),
  invite_request: __table({
    name: 'invite_request',
    indexes: [
      { accessor: 'id', name: 'invite_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'invite_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InviteRequestRow),
  match_event: __table({
    name: 'match_event',
    indexes: [
      { accessor: 'id', name: 'match_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchEventRow),
  match_fixture: __table({
    name: 'match_fixture',
    indexes: [
      { accessor: 'id', name: 'match_fixture_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_fixture_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchFixtureRow),
  match_player: __table({
    name: 'match_player',
    indexes: [
      { accessor: 'id', name: 'match_player_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchPlayerRow),
  match_prediction: __table({
    name: 'match_prediction',
    indexes: [
      { accessor: 'id', name: 'match_prediction_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_prediction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchPredictionRow),
  province: __table({
    name: 'province',
    indexes: [
      { accessor: 'id', name: 'province_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'province_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'province_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'province_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ProvinceRow),
  rate_limit: __table({
    name: 'rate_limit',
    indexes: [
      { accessor: 'id', name: 'rate_limit_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rate_limit_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RateLimitRow),
  rating: __table({
    name: 'rating',
    indexes: [
      { accessor: 'id', name: 'rating_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rating_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RatingRow),
  rating_intent: __table({
    name: 'rating_intent',
    indexes: [
      { accessor: 'identity', name: 'rating_intent_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'rating_intent_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, RatingIntentRow),
  rating_ping: __table({
    name: 'rating_ping',
    indexes: [
      { accessor: 'id', name: 'rating_ping_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rating_ping_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RatingPingRow),
  rating_tag: __table({
    name: 'rating_tag',
    indexes: [
      { accessor: 'id', name: 'rating_tag_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rating_tag_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RatingTagRow),
  rating_vote: __table({
    name: 'rating_vote',
    indexes: [
      { accessor: 'id', name: 'rating_vote_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rating_vote_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RatingVoteRow),
  session: __table({
    name: 'session',
    indexes: [
      { accessor: 'identity', name: 'session_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'session_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, SessionRow),
  snack: __table({
    name: 'snack',
    indexes: [
      { accessor: 'id', name: 'snack_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'snack_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SnackRow),
  snack_like: __table({
    name: 'snack_like',
    indexes: [
      { accessor: 'id', name: 'snack_like_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'snack_like_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SnackLikeRow),
  snack_stats: __table({
    name: 'snack_stats',
    indexes: [
      { accessor: 'snack_id', name: 'snack_stats_snack_id_idx_btree', algorithm: 'btree', columns: [
        'snackId',
      ] },
    ],
    constraints: [
      { name: 'snack_stats_snack_id_key', constraint: 'unique', columns: ['snackId'] },
    ],
  }, SnackStatsRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'id', name: 'user_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'screen_name', name: 'user_screen_name_idx_btree', algorithm: 'btree', columns: [
        'screenName',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'user_screen_name_key', constraint: 'unique', columns: ['screenName'] },
    ],
  }, UserRow),
  user_position: __table({
    name: 'user_position',
    indexes: [
      { accessor: 'user_id', name: 'user_position_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_position_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserPositionRow),
  user_reaction: __table({
    name: 'user_reaction',
    indexes: [
      { accessor: 'id', name: 'user_reaction_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'user_reaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserReactionRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_group_invite", AcceptGroupInviteReducer),
  __reducerSchema("add_city", AddCityReducer),
  __reducerSchema("add_club", AddClubReducer),
  __reducerSchema("add_snack", AddSnackReducer),
  __reducerSchema("approve_invite_request", ApproveInviteRequestReducer),
  __reducerSchema("begin_rating", BeginRatingReducer),
  __reducerSchema("clear_club_mood", ClearClubMoodReducer),
  __reducerSchema("create_group", CreateGroupReducer),
  __reducerSchema("create_group_invite", CreateGroupInviteReducer),
  __reducerSchema("create_match_fixture", CreateMatchFixtureReducer),
  __reducerSchema("delete_match_fixture", DeleteMatchFixtureReducer),
  __reducerSchema("end_rating", EndRatingReducer),
  __reducerSchema("enter_match_result", EnterMatchResultReducer),
  __reducerSchema("join_club", JoinClubReducer),
  __reducerSchema("kick_group_member", KickGroupMemberReducer),
  __reducerSchema("leave_club", LeaveClubReducer),
  __reducerSchema("leave_group", LeaveGroupReducer),
  __reducerSchema("regenerate_group_invite", RegenerateGroupInviteReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("reject_invite_request", RejectInviteRequestReducer),
  __reducerSchema("rename_group", RenameGroupReducer),
  __reducerSchema("request_team_invite", RequestTeamInviteReducer),
  __reducerSchema("revoke_group_invite", RevokeGroupInviteReducer),
  __reducerSchema("seed_clubs", SeedClubsReducer),
  __reducerSchema("send_reaction", SendReactionReducer),
  __reducerSchema("set_avatar", SetAvatarReducer),
  __reducerSchema("set_position", SetPositionReducer),
  __reducerSchema("share_season_with_crew", ShareSeasonWithCrewReducer),
  __reducerSchema("simulate_match", SimulateMatchReducer),
  __reducerSchema("submit_prediction", SubmitPredictionReducer),
  __reducerSchema("submit_rating", SubmitRatingReducer),
  __reducerSchema("toggle_follow", ToggleFollowReducer),
  __reducerSchema("toggle_like", ToggleLikeReducer),
  __reducerSchema("vote_club_mood", VoteClubMoodReducer),
  __reducerSchema("vote_rating", VoteRatingReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

