// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  groupId: __t.u64().name("group_id"),
  opponentClubId: __t.u64().name("opponent_club_id"),
  weAreHome: __t.bool().name("we_are_home"),
  kickoffAt: __t.timestamp().name("kickoff_at"),
  createdBy: __t.u64().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  finalHomeScore: __t.u32().name("final_home_score"),
  finalAwayScore: __t.u32().name("final_away_score"),
  finalEntered: __t.bool().name("final_entered"),
});
