// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  snackId: __t.u64().primaryKey().name("snack_id"),
  clubId: __t.u64().name("club_id"),
  sumScore: __t.u64().name("sum_score"),
  ratingCount: __t.u64().name("rating_count"),
  avgScoreX100: __t.u32().name("avg_score_x_100"),
  lastRatedAt: __t.timestamp().name("last_rated_at"),
});
