// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActivityEvent = __t.object("ActivityEvent", {
  id: __t.u64(),
  get kind() {
    return ActivityKind;
  },
  clubId: __t.u64(),
  userId: __t.u64(),
  snackId: __t.u64(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type ActivityEvent = __Infer<typeof ActivityEvent>;

// The tagged union or sum type for the algebraic type `ActivityKind`.
export const ActivityKind = __t.enum("ActivityKind", {
  UserRegistered: __t.unit(),
  ClubAdded: __t.unit(),
  SnackAdded: __t.unit(),
  RatingSubmitted: __t.unit(),
  SnackClimbed: __t.unit(),
});
export type ActivityKind = __Infer<typeof ActivityKind>;

export const BackupSecret = __t.object("BackupSecret", {
  id: __t.u64(),
  codeHash: __t.string(),
  userId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type BackupSecret = __Infer<typeof BackupSecret>;

export const City = __t.object("City", {
  id: __t.u64(),
  provinceId: __t.u64(),
  name: __t.string(),
  nameKey: __t.string(),
});
export type City = __Infer<typeof City>;

export const Club = __t.object("Club", {
  id: __t.u64(),
  name: __t.string(),
  nameKey: __t.string(),
  provinceId: __t.u64(),
  cityId: __t.u64(),
  createdBy: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Club = __Infer<typeof Club>;

export const ClubMembership = __t.object("ClubMembership", {
  id: __t.u64(),
  userId: __t.u64(),
  clubId: __t.u64(),
  joinedAt: __t.timestamp(),
});
export type ClubMembership = __Infer<typeof ClubMembership>;

export const ClubMood = __t.object("ClubMood", {
  id: __t.u64(),
  clubId: __t.u64(),
  userId: __t.u64(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type ClubMood = __Infer<typeof ClubMood>;

export const Follow = __t.object("Follow", {
  id: __t.u64(),
  followerId: __t.u64(),
  followeeId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Follow = __Infer<typeof Follow>;

export const FootballMatch = __t.object("FootballMatch", {
  id: __t.u64(),
  homeClubId: __t.u64(),
  awayClubId: __t.u64(),
  homeIsGroup: __t.bool(),
  awayIsGroup: __t.bool(),
  homeScore: __t.u32(),
  awayScore: __t.u32(),
  seed: __t.u64(),
  createdBy: __t.u64(),
  createdAt: __t.timestamp(),
  ballX: __t.f32(),
  ballY: __t.f32(),
  ballVx: __t.f32(),
  ballVy: __t.f32(),
  ballTargetX: __t.f32(),
  ballTargetY: __t.f32(),
  phase: __t.string(),
  phaseSetAt: __t.timestamp(),
  lastActionPlayerId: __t.u64(),
  lastActionSide: __t.string(),
  ballCarrierId: __t.u64(),
  possessionSide: __t.string(),
  nextDecisionAt: __t.timestamp(),
  simPausedUntil: __t.timestamp(),
  isLive: __t.bool(),
});
export type FootballMatch = __Infer<typeof FootballMatch>;

export const Group = __t.object("Group", {
  id: __t.u64(),
  name: __t.string(),
  nameKey: __t.string(),
  ownerUserId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Group = __Infer<typeof Group>;

export const GroupInvite = __t.object("GroupInvite", {
  id: __t.u64(),
  groupId: __t.u64(),
  invitedBy: __t.u64(),
  expiresAt: __t.timestamp(),
  maxUses: __t.u32(),
  uses: __t.u32(),
  createdAt: __t.timestamp(),
});
export type GroupInvite = __Infer<typeof GroupInvite>;

export const GroupMembership = __t.object("GroupMembership", {
  id: __t.u64(),
  groupId: __t.u64(),
  userId: __t.u64(),
  joinedAt: __t.timestamp(),
});
export type GroupMembership = __Infer<typeof GroupMembership>;

export const InviteRequest = __t.object("InviteRequest", {
  id: __t.u64(),
  groupId: __t.u64(),
  fromUserId: __t.u64(),
  requestedAt: __t.timestamp(),
});
export type InviteRequest = __Infer<typeof InviteRequest>;

export const InviteSecret = __t.object("InviteSecret", {
  id: __t.u64(),
  code: __t.string(),
  inviteId: __t.u64(),
});
export type InviteSecret = __Infer<typeof InviteSecret>;

export const MatchEvent = __t.object("MatchEvent", {
  id: __t.u64(),
  matchId: __t.u64(),
  minute: __t.u32(),
  get kind() {
    return MatchEventKind;
  },
  teamSide: __t.string(),
  matchPlayerId: __t.u64(),
  text: __t.string(),
});
export type MatchEvent = __Infer<typeof MatchEvent>;

// The tagged union or sum type for the algebraic type `MatchEventKind`.
export const MatchEventKind = __t.enum("MatchEventKind", {
  KickOff: __t.unit(),
  Goal: __t.unit(),
  SaveByKeeper: __t.unit(),
  Miss: __t.unit(),
  Corner: __t.unit(),
  Tackle: __t.unit(),
  HalfTime: __t.unit(),
  FullTime: __t.unit(),
});
export type MatchEventKind = __Infer<typeof MatchEventKind>;

export const MatchFixture = __t.object("MatchFixture", {
  id: __t.u64(),
  groupId: __t.u64(),
  opponentClubId: __t.u64(),
  weAreHome: __t.bool(),
  kickoffAt: __t.timestamp(),
  createdBy: __t.u64(),
  createdAt: __t.timestamp(),
  finalHomeScore: __t.u32(),
  finalAwayScore: __t.u32(),
  finalEntered: __t.bool(),
});
export type MatchFixture = __Infer<typeof MatchFixture>;

export const MatchPlayer = __t.object("MatchPlayer", {
  id: __t.u64(),
  matchId: __t.u64(),
  side: __t.string(),
  slot: __t.string(),
  userId: __t.u64(),
  botSlot: __t.u32(),
  displayName: __t.string(),
  avatarColor: __t.string(),
  avatarIcon: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
});
export type MatchPlayer = __Infer<typeof MatchPlayer>;

export const MatchPosTick = __t.object("MatchPosTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type MatchPosTick = __Infer<typeof MatchPosTick>;

export const MatchPrediction = __t.object("MatchPrediction", {
  id: __t.u64(),
  fixtureId: __t.u64(),
  userId: __t.u64(),
  homeScore: __t.u32(),
  awayScore: __t.u32(),
  pointsAwarded: __t.u32(),
  scored: __t.bool(),
  submittedAt: __t.timestamp(),
});
export type MatchPrediction = __Infer<typeof MatchPrediction>;

export const MatchPredictionSecret = __t.object("MatchPredictionSecret", {
  id: __t.u64(),
  predictionId: __t.u64(),
  homeScore: __t.u32(),
  awayScore: __t.u32(),
});
export type MatchPredictionSecret = __Infer<typeof MatchPredictionSecret>;

export const MatchTick = __t.object("MatchTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
  minute: __t.u32(),
});
export type MatchTick = __Infer<typeof MatchTick>;

export const Province = __t.object("Province", {
  id: __t.u64(),
  name: __t.string(),
});
export type Province = __Infer<typeof Province>;

export const RateLimit = __t.object("RateLimit", {
  id: __t.u64(),
  identity: __t.identity(),
  action: __t.string(),
  lastAt: __t.timestamp(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const Rating = __t.object("Rating", {
  id: __t.u64(),
  userId: __t.u64(),
  clubId: __t.u64(),
  snackId: __t.u64(),
  score: __t.u8(),
  reviewText: __t.string(),
  createdAt: __t.timestamp(),
});
export type Rating = __Infer<typeof Rating>;

export const RatingIntent = __t.object("RatingIntent", {
  identity: __t.identity(),
  userId: __t.u64(),
  snackId: __t.u64(),
  startedAt: __t.timestamp(),
});
export type RatingIntent = __Infer<typeof RatingIntent>;

export const RatingPing = __t.object("RatingPing", {
  id: __t.u64(),
  ratingId: __t.u64(),
  fromUserId: __t.u64(),
  toUserId: __t.u64(),
  snackId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type RatingPing = __Infer<typeof RatingPing>;

export const RatingReaction = __t.object("RatingReaction", {
  id: __t.u64(),
  ratingId: __t.u64(),
  userId: __t.u64(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type RatingReaction = __Infer<typeof RatingReaction>;

export const RatingTag = __t.object("RatingTag", {
  id: __t.u64(),
  ratingId: __t.u64(),
  snackId: __t.u64(),
  clubId: __t.u64(),
  tag: __t.string(),
});
export type RatingTag = __Infer<typeof RatingTag>;

export const RatingVote = __t.object("RatingVote", {
  id: __t.u64(),
  ratingId: __t.u64(),
  voterUserId: __t.u64(),
  value: __t.i8(),
  createdAt: __t.timestamp(),
});
export type RatingVote = __Infer<typeof RatingVote>;

export const Session = __t.object("Session", {
  identity: __t.identity(),
  userId: __t.u64(),
  connectedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const Snack = __t.object("Snack", {
  id: __t.u64(),
  clubId: __t.u64(),
  name: __t.string(),
  nameKey: __t.string(),
  createdBy: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Snack = __Infer<typeof Snack>;

export const SnackLike = __t.object("SnackLike", {
  id: __t.u64(),
  userId: __t.u64(),
  snackId: __t.u64(),
  clubId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type SnackLike = __Infer<typeof SnackLike>;

export const SnackStats = __t.object("SnackStats", {
  snackId: __t.u64(),
  clubId: __t.u64(),
  sumScore: __t.u64(),
  ratingCount: __t.u64(),
  avgScoreX100: __t.u32(),
  lastRatedAt: __t.timestamp(),
});
export type SnackStats = __Infer<typeof SnackStats>;

export const User = __t.object("User", {
  id: __t.u64(),
  identity: __t.identity(),
  screenName: __t.string(),
  screenNameKey: __t.string(),
  createdAt: __t.timestamp(),
  avatarColor: __t.string(),
  avatarIcon: __t.string(),
  avatarDecor: __t.string(),
});
export type User = __Infer<typeof User>;

export const UserPosition = __t.object("UserPosition", {
  userId: __t.u64(),
  position: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserPosition = __Infer<typeof UserPosition>;

export const UserReaction = __t.object("UserReaction", {
  id: __t.u64(),
  fromUserId: __t.u64(),
  toUserId: __t.u64(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type UserReaction = __Infer<typeof UserReaction>;

