// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  screenName: __t.string().name("screen_name"),
  screenNameKey: __t.string().name("screen_name_key"),
  createdAt: __t.timestamp().name("created_at"),
  avatarColor: __t.string().name("avatar_color"),
  avatarIcon: __t.string().name("avatar_icon"),
  avatarDecor: __t.string().name("avatar_decor"),
});
